name: Release Broadcast
on:
  release:
    types: [created]

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.BROADCAST_PASSWORD }}" -d '${{ toJson(github.event.release) }}' ${{ secrets.RELEASE_BROADCAST_ENDPOINT }}
